apiVersion: apps/v1
kind: Deployment
metadata:
  name: acme-assist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acme-assist
  template:
    metadata:
      labels:
        app: acme-assist
    spec:
      containers:
        - name: acme-assist
          image: localhost:5001/acme-assist:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "local"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://assist-postgres:5432/acme-assist"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "rootpassword"

            - name: SPRING_CLOUD_CONFIG_IMPORT
              value: "configserver:http://config-server:8888"

            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-discovery:8761/eureka"


---
apiVersion: v1
kind: Service
metadata:
  name: acme-assist
spec:
  selector:
    app: acme-assist
  ports:
    - name: http
      port: 8081
      targetPort: 8081
