apiVersion: apps/v1
kind: Deployment
metadata:
  name: acme-shopping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acme-shopping
  template:
    metadata:
      labels:
        app: acme-shopping
    spec:
      containers:
        - name: acme-shopping
          image: localhost:5001/acme-shopping:latest
          ports:
            - containerPort: 8080
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-discovery:8761/eureka"
---
apiVersion: v1
kind: Service
metadata:
  name: acme-shopping
spec:
  selector:
    app: acme-shopping
  ports:
    - port: 8080
      targetPort: 8080
      name: http
