apiVersion: apps/v1
kind: Deployment
metadata:
  name: assist-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assist-postgres
  template:
    metadata:
      labels:
        app: assist-postgres
    spec:
      containers:
        - name: assist-postgres
          image: pgvector/pgvector:pg16
          env:
            - name: POSTGRES_USER
              value: root
            - name: POSTGRES_PASSWORD
              value: rootpassword
            - name: POSTGRES_DB
              value: acme-assist
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: assist-postgres
spec:
  selector:
    app: assist-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
