apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: config-server
        image: steeltoeoss/config-server:latest
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "native"
          - name: SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS
            value: "file:///config"
        volumeMounts:
          - name: config-volume
            mountPath: /config
        ports:
          - containerPort: 8888
      volumes:
        - name: config-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
spec:
  selector:
    app: config-server
  ports:
    - port: 8888
      targetPort: 8888
      name: config

