apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-discovery
  template:
    metadata:
      labels:
        app: eureka-discovery
    spec:
      containers:
      - name: eureka-discovery
        image: steeltoeoss/eureka-server:latest
        ports:
          - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-discovery
spec:
  selector:
    app: eureka-discovery
  ports:
    - port: 8761
      targetPort: 8761
      name: eureka

