apiVersion: v1
kind: Service
metadata:
  name: gateway-auth-nodeport
spec:
  type: NodePort
  selector:
    app: gateway-auth
  ports:
    - name: gateway
      port: 8090
      targetPort: 8090
      nodePort: 30090
    - name: auth
      port: 9000
      targetPort: 9000
      nodePort: 30091

