server:
  port: 8084

spring:
  cloud:
    config:
      enabled: true
  config:
    import:
      - configserver:http://config-server:8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-discovery:8761/eureka