apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: joomla
  namespace: default
spec:
  serviceAccountName: fluxcd-helmrelease-installer
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: joomla
      sourceRef:
        kind: HelmRepository
        name: bitnami
      interval: 5m