apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: joomla
  generateName: "true"
spec:
  serviceAccountName: fluxcd-helmrelease-installer
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: joomla
      version: '20.0.4'
      sourceRef:
        kind: HelmRepository
        name: bitnami
      interval: 5m
  releaseName: joomla
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3