
management:
  endpoints:
    web:
      exposure:
        include: info,health
spring:
  ai:
    openai:
      chat:
        options:
          functions:
            - terrainFunction
            - displayRecommendation
    vectorstore:
      pgvector: 
        initialize-schema: true
        remove-existing-vector-store-table: true
  application:
    name: acme-assist
  cloud:
    config:
      enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
