spring:
  application:
    name: acme-catalog

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    encoding: UTF-8

eureka:
  client:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: info,health
